services:
  database:
    image: mysql:8.0
    container_name: mysql-container
    env_file:
      - ./.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backEnd  
    container_name: backend
    env_file:
     - ./backend/.env
    ports:
      - 3000:3000
    depends_on:
      - database
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - backend
    ports:
      - 80:80
    networks:
      - app-network

volumes:
  db_data:
    driver: local

networks:
  app-network: 
    driver: bridge 